export const imageData = [
  {
    name: "Big Benz",
    price: "$2000",
    src: "https://itarkett.sirv.com/Images/ipencil_arts/bigbenz.jpeg",
    size:'3ft x 4ft',
    year:2023,
  },
  {
    name: "Blue Series 1",
    price: "$2000",
    src: "https://itarkett.sirv.com/Images/ipencil_arts/blueseries_1.jpeg",
    size:'3ft x 4ft',
    year:2023,
  },
  {
    name: "Blue Series 2",
    price: "$2000",
    src: "https://itarkett.sirv.com/Images/ipencil_arts/blueseries_2.jpeg",
    size:'3ft x 4ft',
    year:2023,
  },
  {
    name: "Blue Series 3",
    price: "$2000",
    src: "https://itarkett.sirv.com/Images/ipencil_arts/blueseries_3.jpeg",
    size:'3ft x 4ft',
    year:2023,
  },
  {
    name: "Vanity Upon Vanity",
    price: "$2000",
    src: "https://itarkett.sirv.com/Images/ipencil_arts/vanityuponvanity.jpeg",
    size:'3ft x 4ft',
    year:2023,
  },
  {
    name: "Court Maestero",
    price: "$2000",
    src: "https://itarkett.sirv.com/Images/ipencil_arts/courtmaestero.jpeg",
    size:'3ft x 4ft',
    year:2023,
  },
  {
    name: "Blind to Color",
    price: "$2000",
    src: "https://itarkett.sirv.com/Images/ipencil_arts/blindtocolour.jpeg",
    size:'3ft x 4ft',
    year:2023,
  },
  {
    name: "All Back",
    price: "$2000",
    src: "https://itarkett.sirv.com/Images/ipencil_arts/All%20Black.jpeg",
    size:'3ft x 4ft',
    year:2023,
  },
];
