export const prints = [
  {
    name: "Man in purple",
    price: 250,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/man_in_purple.jpeg",
    size: "16 x 20 inches",
    year: 2025,
    quantity: 1,
  },
  {
    name: "The Sojourner 2",
    price: 250,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/the_sojourner_2.jpeg",
    size: "16 x 20 inches",
    year: 2025,
    quantity: 1,
  },
  {
    name: "Flower Boy",
    price: 250,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/flower_boy.jpeg",
    size: "16 x 20 inches",
    year: 2025,
    quantity: 1,
  },
  {
    name: "Blue Series 3",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/blueseries_3.jpeg",
    size: "16 x 20 inches",
    year: 2023,
    quantity: 1,
  },
  {
    name: "Blue Series 1",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/blueseries_1.jpeg",
    size: "16 x 20 inches",
    year: 2023,
    quantity: 1,
  },

  {
    name: "All Back",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/All%20Black.jpeg",
    size: "16 x 20 inches",
    year: 2023,
    quantity: 1,
  },

  {
    name: "Vanity Upon Vanity",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/vanityuponvanity.jpeg",
    size: "16 x 20 inches",
    year: 2023,
    quantity: 1,
  },
  {
    name: "Court Maestero",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/courtmaestero.jpeg",
    size: "16 x 20 inches",
    year: 2023,
    quantity: 1,
  },
  {
    name: "Blue Series 2",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/blueseries_2.jpeg",
    size: "16 x 20 inches",
    year: 2023,
    quantity: 1,
  },
  {
    name: "Big Benz",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/bigbenz.jpeg",
    size: "16 x 20 inches",
    year: 2023,
    quantity: 1,
  },
  {
    name: "Blind to Color",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/blindtocolour.jpeg",
    size: "16 x 20 inches",
    year: 2023,
    quantity: 1,
  },
  //descriptions to new collections
  {
    name: "Lady In Pink",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/Lady_In_Pink.jpeg",
    size: "16 x 20 inches",
    year: 2024,
    quantity: 1,
  },
  {
    name: "Lady In Red",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/Lady_in_red.jpeg",
    size: "16 x 20 inches",
    year: 2024,
    quantity: 1,
  },
  {
    name: "Sisters",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/Sisters.jpeg",
    size: "16 x 20 inches",
    year: 2024,
    quantity: 1,
  },
  {
    name: "African Queen",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/African_Queen.jpeg",
    size: "16 x 20 inches",
    year: 2024,
    quantity: 1,
  },
  {
    name: "Ada",
    price: 140,
    src: "https://itarkett.sirv.com/Images/ipencil_arts/Ada.jpeg",
    size: "16 x 20 inches",
    year: 2024,
    quantity: 1,
  },
];
